// ==UserScript==
// @name         SteinDamageMeter
// @version      2.0.19
// @description  Useful tools for stein.world
// @author       frydrom
// @homepage     https://steindamagemeter.netlify.app/
// @match        https://*.stein.world/game*
// @grant        none
// @run-at       document-start
// ==/UserScript==
(function(){try{(function(){function L(){R++;"undefined"!==typeof isGameReady&&isGameReady()?null!==z&&0===z.length||"undefined"===typeof subscribeEvents||subscribeEvents(ea):""===C?console.log("count",R,C):1E3<R?console.log("Too many loops."):setTimeout(L,0)}function ea(c){if(null!==z&&0!==z.length){var e=c.indexOf('"',10);if(-1!==e&&(e=parseInt(c.substring(10,e),10),z.includes(e)))if(c=JSON.parse(c),293===e)G.classList.add("--sdm-in-combat");else if(294===e)G.classList.remove("--sdm-in-combat");else if(3===
e){var f=c.a,m=c.d;if(f in A){var h=p.F;if(S===f&&h){e=c.b.a;var k=null;0===e?k=h:1===e?k=p.D:2===e&&(k=p.G);null!==k&&(k.innerText=`${c.b.b}`)}h=c?0===c.b.a?c.b:null:null;null!==h&&(m in H&&(e=A[f]-h.b,0<e&&2===c.c&&m!==f&&(c=H[m],"DEFAULT"===B?(w[c]+=e,M=!0):(k=T.get(f),void 0!==k&&(m=N.get(k),void 0===m&&(m=new Map,m.set(0,Date.now()),N.set(k,m),U.push(k)),k=m.get(c)||0,m.set(c,k+e),m.set(1,Date.now()),M=!0)),null===O&&"DEFAULT"===B&&(c=T.get(f))&&(O=c),I=Date.now(),null===D&&(D=I))),A[f]=h.b)}}else{2===
e?h=[c]:h=c.a;for(f of h)a:if(c=fa(f),null!==c){c=c.b;switch(f.b){case 0:S=f.a;case 1:h=f.m;H[f.a]=h;h in w||(w[h]=0);break;case 6:f.a in A||!(5E4<c||"DEFAULT"!==B)||(h=f.m,"SPLIT"===B&&(e=(Z.get(h)||0)+1,Z.set(h,e),1!==e&&(h=`${h} (${e})`)),T.set(f.a,h));break;default:break a}A[f.a]=c}}}}function fa(c){return c?(c=c.j)&&c.length?c.find(e=>0===e.a)||null:null:null}function aa(c){function e(a,b,d,g){b=Math.max(b,250);const l=`${Math.round(b/10)/100}s`;a=(g?`${d} | Time: ${l}\n`:"")+a.sort((n,v)=>v[1]-
n[1]).filter(n=>c||0<n[1]).map((n,v)=>{var J=n[0];a:{var q=n[1];if(1E3>q){if(0===q){q="0";break a}q/=1E3}else q=Math.round(q/100)/10;q=`${q}k`}return`${v+1}. ${J}: ${q} (${Math.round(n[1]/b*1E4)/10} dps)`}).join(",\n");g||(a+=`\nTotal time${d?` (${d})`:""}: ${l}.`);return a}if("DEFAULT"===B)return e(Object.keys(w).map(a=>[a,w[a]]),I-D,O,!1);const f=[];var m=Infinity;let h=-Infinity;for(const a of U){var k=N.get(a);const b=k.get(0),d=k.get(1);m=Math.min(m,b);h=Math.max(h,d);k=[...k].filter(([g])=>
0!==g&&1!==g);f.push(e(k,d-b,a,!0))}m=1<f.length?`\n\nTotal time: ${`${Math.round(Math.max(h-m,250)/10)/100}s`}.`:"";return f.reverse().join("\n\n").trim()+m}function ha(){if(null!==D&&!1!==M){M=!1;if(r.DAMAGE_METER?.s){var c=aa(!1);const e=c.split("\n").length;p.v.innerText=c;c=Math.min(Math.floor(714/e/1.2),16);p.v.style.fontSize=`${c}px`;p.v.classList.toggle("--sdm-lot-of-text",16!==c)}r.PERSONAL_DPS?.s&&(c=w[H[S]])&&(p.A.innerText=`${Math.round(c/Math.max(I-D,250)*1E4)/10} dps`)}}function ia(){for(const c of Object.keys(A))0!==
A[c]||c in H||delete A[c];for(const c of Object.keys(w))w[c]=0;I=D=O=null;p.v.innerText="";p.A&&(p.A.innerText="");N=new Map;U=[]}function V(c,e){e?(P&&(c=P+"\n"+c),P=c):P=null;e=document.createElement("textarea");e.value=c;t.appendChild(e);e.select();document.execCommand("copy");t.removeChild(e)}function E(c,e){const f=document.createElement("div");f.id=c;f.className="--sdm-scale-with-render-distance --sdm-svg-overlay";f.innerHTML=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="-110 -110 220 220"><g>${e}</g></svg>`;
t.appendChild(f)}function ba(){return!x||x.getItem("sdm--force-disable")||window["sdm--force-disable-v2.0.19"]?!0:window["sdm--force-disable"]?(x.setItem("sdm--force-disable","1"),!0):!1}function K(c){if("undefined"!==typeof setRenderDistance){setRenderDistance(c);x.setItem("smd--render-distance",""+c);var e=ca(".--sdm-scale-with-render-distance");for(const f of e)f.style.transform=15===c?"":`scale(${15/c},${15/c})`}}function Q(){x.setItem("sdm--config--2.0.1",JSON.stringify(W))}let C=null;const x=
window.localStorage;if(!ba()){var M=!1,ca=document.querySelectorAll.bind(document),F=document.querySelector.bind(document),W=JSON.parse(x.getItem("sdm--config--2.0.1")||"{}"),G=null,t=null,ja=0,r={},X=[],P=null,u=15,Y=!1,R=0,z=null,p={},B="DEFAULT",S=null,D=null,I=null,w={},U=[],N=new Map,H={},A={},T=new Map,Z=new Map,O=null,y={capture:!1,passive:!0};L();document.addEventListener("DOMContentLoaded",()=>{function c(a,b){if(!0!==Y){b.name=a;b.id="--sdm-f"+ja++;a in f||(f[a]={});b.u=!1!==b.u;var d=b.u?
!!f[a].enabled:!0;b.o=f[a].enabled=d;b.l=!0===b.l;b.s=f[a].active=d?b.l?!!f[a].active:!0:!1;r[b.name]=b;if(b.o&&(b.h?.includes("FEATURE_ACTIVE")&&(b.h=b.h.replaceAll("FEATURE_ACTIVE",`html.${b.id}`)),b.h&&X.push(b.h),b.s&&G.classList.toggle(b.id,!0),b.i))try{b.i(b)}catch(g){console.error(g),Y=!0}}}function e(a,b){void 0===b||null===b?a.s=!a.s:a.s=b;G.classList.toggle(a.id,a.s);a.B&&a.B.classList.toggle("--sdm-toggle-on",a.s);f[a.name].active=a.s;Q()}C="";if(!ba()&&(G=document.documentElement,t=document.body,
C=F(".stein-login-screen-version-info.stein-text-border")?.innerText||F(".stein-version-info")?.innerText||"")){var f=W[C];void 0===f&&(W[C]=f={},Q());var m=[];z=[];c("DAMAGE_METER",{l:!0,g:"Damage meter",i:()=>{z.push(2,3,195);const a=document.createElement("div");a.id="sdm--damage-meter";a.className="--sdm-custom-overlay-item --sdm-events-none";var b=document.createElement("div");b.style.backgroundColor="#a013138c";a.appendChild(b);p.v=b;b=document.createElement("button");b.innerText="Reset";b.type=
"button";b.addEventListener("click",ia,y);b.style.pointerEvents="auto";b.tabIndex=-1;a.appendChild(b);b=document.createElement("button");b.innerText="Copy";b.type="button";b.tabIndex=-1;b.addEventListener("click",()=>{V(aa(!1),!1)},y);b.style.pointerEvents="auto";a.appendChild(b);t.appendChild(a);setInterval(ha,1E3)},h:"#sdm--damage-meter {\n  right: 0;\n  top: 100px;\n  display: none;\n  min-width: 100px;\n}\n\n#sdm--damage-meter > div {\n  line-height: 120%;\n}\n\nFEATURE_ACTIVE #sdm--damage-meter {\n    display: unset;\n}\n\n#sdm--self-dps,\n#sdm--self-resource {\n  bottom: 100px;\n  left: 50%;\n  transform: translateX(-50%);\n  font-size: 28px;\n  font-weight: bold;\n  color: #fff;\n  text-shadow: 1px 0px 0px #000, 0px 1px 0px #000, -1px 0px 0px #000, 0px -0px 0px #000;\n  display: none;\n}\n\n#sdm--self-resource {\n  bottom: 75px;\n}\n\n#sdm--self-resource > span {\n  min-width: 60px;\n  display: inline-block;\n  text-align: center;\n}"});
r.DAMAGE_METER?.o&&(c("SPLIT_DPS",{g:"Show dps separately for each enemy",i:()=>{B="SPLIT"}}),c("SPLIT_DPS_AGGREGATE",{g:"Show dps separately for each enemy type",i:()=>{B="AGGREGATE"}}),c("PERSONAL_DPS",{g:"DPS at the bottom of the screen",l:!0,i:()=>{const a=document.createElement("div");a.id="sdm--self-dps";a.className="--sdm-custom-overlay-item --sdm-events-none";t.appendChild(a);p.A=a},h:"FEATURE_ACTIVE #sdm--self-dps { display: unset; }"}),c("PERSONAL_RESOURCES",{g:"Life/Energy/Mana at the bottom of the screen",
l:!0,i:()=>{const a=document.createElement("div"),b=document.createElement("span"),d=document.createElement("span"),g=document.createElement("span");a.id="sdm--self-resource";a.className="--sdm-custom-overlay-item --sdm-events-none";b.innerText=g.innerText=d.innerText="?";g.style.minWidth="45px";a.append(b);a.append(" | ");a.append(g);a.append(" | ");a.append(d);p.F=b;p.D=g;p.G=d;t.appendChild(a)},h:"FEATURE_ACTIVE #sdm--self-resource { display: unset; }"}));c("COMBAT_INDICATOR",{g:"Combat indicator",
i:()=>{z.push(293,294)},h:"html.--sdm-in-combat #stein-shortcuts-button-container > .--sdm-skull-button {\n  background-image: url(/assets/images/items/axe.png);\n  background-color: red;         \n}"});c("MENU",{u:!1,h:".--sdm-hidden {\n  display: none !important;\n}\n\n.--sdm-custom-overlay-item {\n  color: white;\n  position: fixed;\n  z-index: 99;\n}\n\n.--sdm-events-none {\n  pointer-events: none;\n}\n\n#--sdm-menu {\n  top: 10%;\n  left: 10%;\n  max-height: 90%;\n  overflow: auto;\n\n  background-color: rgba(0, 0, 0, 0.85);\n\n  white-space: pre-wrap;\n  z-index: 999;\n}\n\nFEATURE_ACTIVE #--sdm-menu {\n  display: unset;\n}\n\n.--sdm-toggle {\n  background-color: red;\n}\n\n.--sdm-toggle-on {\n  background-color: green;\n}\n\n#--sdm-menu td {\n  border-bottom: 2px solid white;\n}\n\n.--sdm-skull-button {\n  background-image: url(/assets/images/icon_death_skull.png);\n  background-position: center;\n  background-repeat: no-repeat;\n}\n\n.--sdm-lot-of-text + button {\n  position: absolute;\n  top: -27px;\n}\n\n.--sdm-lot-of-text + button + button {\n  position: absolute;\n  top: -27px;\n  right: 0;\n}",
i:()=>{m.push(()=>{var a=document.createElement("div");a.className="stein-toggle-button --sdm-skull-button";a.addEventListener("click",()=>{b.classList.toggle("--sdm-hidden")},y);document.getElementById("stein-shortcuts-button-container").insertBefore(a,document.getElementById("stein-plus-toggle-button"));document.addEventListener("keydown",d=>{"Escape"===d.key&&b.classList.toggle("--sdm-hidden",!0)},y);const b=document.createElement("div");t.appendChild(b);b.id="--sdm-menu";b.classList.add("--sdm-hidden",
"--sdm-custom-overlay-item");b.innerHTML="\n<table>\n  <thead>\n    <tr>\n      <td>ENABLED</td>\n      <td>ACTIVE<br/>(visible)</td>\n      <td>DamageMeter v2.0.19</td>\n    </tr>\n  </thead>\n  <tbody></tbody>\n</table>\n";a=b.querySelector("tbody");for(const [,d]of Object.entries(r)){if(!d.g)continue;const g=document.createElement("tr"),l=document.createElement("td");g.appendChild(l);d.u&&(l.classList.add("--sdm-toggle"),d.o&&l.classList.add("--sdm-toggle-on"),l.addEventListener("click",()=>{d.o=
!d.o;d.C&&d.C.classList.toggle("--sdm-toggle-on",d.o);d.l&&e(d,d.o);f[d.name].enabled=d.o;Q()},y));const n=document.createElement("td");g.appendChild(n);d.l&&(n.classList.add("--sdm-toggle"),d.s&&n.classList.add("--sdm-toggle-on"),n.addEventListener("click",()=>{d.o&&e(d,null)},y));const v=document.createElement("td");v.textContent=d.g;g.appendChild(v);a.appendChild(g);d.C=l;d.B=n}})}});c("CLIPBOARD",{g:"Copy to clipboard\n• ctrl+click on item to copy stats to clipboard\n• ctrl+click on chat message to copy it to clipboard (hold alt to copy with time and player)\n• hold shift to copy multiple stuff at once",
i:()=>{document.getElementById("stein-chat-content-container").addEventListener("click",a=>{if(a.ctrlKey){let b=a.target;if(a.altKey)for(;!b.parentElement.classList.contains("stein-chat-content");)b=b.parentElement;V(b.textContent,a.shiftKey)}},y);document.addEventListener("mousedown",a=>{if(a.ctrlKey){var b=document.getElementById("stein-tooltip");if("none"!==b.style.display){b=[b];const l=[];for(;0!==b.length;){var d=b.pop();if(3===d.nodeType)(d=(d.textContent||"").trim())&&l.push(d);else{var g=
(d=d.childNodes)?d.length:0;for(--g;0<=g;g--)b.push(d[g])}}V("["+l.join(" | ")+"]",a.shiftKey)}}},y)}});c("UNLOAD",{g:"Prevent accidental closing/refreshing (hover skull icon to skip confirmations).",i:()=>{window.addEventListener("beforeunload",a=>{"none"===F("#stein-login-screen")?.style?.display&&"none"===F("#stein-options-screen")?.style?.display&&"none"===F("#stein-logout-overlay")?.style?.display&&null===F(".--sdm-skull-button:hover")&&(a.preventDefault(),a.returnValue="")})}});c("NO-BLUR",
{g:"Keep moving when alt-tabbed.",i:()=>{const a=EventTarget.prototype.addEventListener;EventTarget.prototype.addEventListener=function(b,d,g){this===window&&"blur"===b&&"()=>{_._=_();_._=!0}"===d.toString().replaceAll(/[a-zA-Z]+/g,"_")||a.apply(this,[b,d,g])}}});c("NO-CLICKS",{g:"Unbind left and right mouse buttons (when ctrl is not pressed)",i:()=>{const a=EventTarget.prototype.addEventListener;EventTarget.prototype.addEventListener=function(b,d,g){this===window&&"mousedown"===b&&"_=>{_._(_)}"===
d.toString().replaceAll(/[a-zA-Z]+/g,"_")?a.apply(this,[b,l=>{l.ctrlKey&&d(l)},g]):a.apply(this,[b,d,g])}}});c("UI",{g:"Basic UI tweaks",l:!0,i:()=>{for(const a of"stein-party-leave-button stein-inventory-trash-confirm-button-trash stein-item-amount-all-confirm stein-item-amount-confirm stein-chat-send stein-party-invite-button".split(" ")){const b=document.getElementById(a);b&&(b.tabIndex=-1)}},h:'FEATURE_ACTIVE #stein-logout-overlay {\n  bottom: auto;\n  pointer-events: none;\n}\n\nFEATURE_ACTIVE #stein-trade-window-buy-gems:not([style*="none"]) ~ #stein-trade-window-buy-back {\n  display: block !important;\n}\n\nFEATURE_ACTIVE .stein-dropped-item-background {\n  display: none;\n}\n\nFEATURE_ACTIVE #stein-target-container,\nFEATURE_ACTIVE #stein-player-container {\n  opacity: 0.85;\n}\n\nFEATURE_ACTIVE #stein-hub-window,\nFEATURE_ACTIVE #stein-options-screen,\nFEATURE_ACTIVE #stein-tooltip,\nFEATURE_ACTIVE #stein-target-container,\nFEATURE_ACTIVE #stein-logout-overlay-content,\nFEATURE_ACTIVE #stein-target-forms,\nFEATURE_ACTIVE #stein-player-container,\nFEATURE_ACTIVE #stein-player-forms,\nFEATURE_ACTIVE #stein-party-container,\nFEATURE_ACTIVE #stein-chat-container {\n  pointer-events: none;\n}\n\nFEATURE_ACTIVE #stein-logout-buttons,\nFEATURE_ACTIVE #stein-options-form,\nFEATURE_ACTIVE #stein-hub-window > div > div,\nFEATURE_ACTIVE #stein-target-buffs,\nFEATURE_ACTIVE #stein-player-buffs > div,\nFEATURE_ACTIVE #stein-chat-tabs > *,\nFEATURE_ACTIVE #stein-chat-container-input,\nFEATURE_ACTIVE #stein-chat-content-container,\nFEATURE_ACTIVE #stein-party-invite,\nFEATURE_ACTIVE #stein-party-member-list,\nFEATURE_ACTIVE #stein-party-invite-member-container,\nFEATURE_ACTIVE #stein-party-invite-accept-container {\n  pointer-events: auto;\n}\n\nFEATURE_ACTIVE .stein-hub-friend-list-entry:hover {\n  background-color: grey;\n}\n\nFEATURE_ACTIVE #stein-respawn-screen {\n  z-index: 3 !important;\n}\n\nFEATURE_ACTIVE #stein-cast-bar-container {\n  z-index: 999 !important;\n}\n\nhtml, body {\n  background-color: #000;\n}'});
c("UI2",{g:"Additional UI tweaks (hides some elements and animations)",l:!0,h:'FEATURE_ACTIVE .stein-dropped-item-container.inventory-transition,\nFEATURE_ACTIVE #stein-logout-buttons,\nFEATURE_ACTIVE a[href="http://steingame.wikia.com/wiki/FAQ"],\nFEATURE_ACTIVE #stein-experience-bar {\n  display: none !important;\n}\n\nFEATURE_ACTIVE .stein-collection-group-item {\n    filter: contrast(0.7) grayscale(0.5);\n}'});c("CHAT",{g:"Make chat bigger, with darker background.",l:!0,h:"FEATURE_ACTIVE #stein-chat-container {\n  max-height: 400px;\n}\n\nFEATURE_ACTIVE #stein-chat-content-container {\n  background-color: rgba(0, 0, 0, 0.7);\n}"});
c("WIDE",{g:"Wider inventory",l:!0,h:"FEATURE_ACTIVE #stein-inventory-slots {\n    max-width: 728px;\n}"});c("QUICKBAR",{g:"Inventory: don't scroll quickbar",l:!0,h:"FEATURE_ACTIVE #stein-inventory-title-quickbar,\nFEATURE_ACTIVE #stein-inventory-title-backpack {\n    display: none;\n}\n\nFEATURE_ACTIVE #stein-inventory-quick-bar-slots {\n    position: absolute;\n    z-index: 1;\n    margin-top: -56px;\n}\n\nFEATURE_ACTIVE #stein-inventory-scroll-container {\n    margin-top: 56px;\n}"});var h=x.getItem("sdm--custom-css");
if(h){let a;if(h.startsWith("{"))try{a=JSON.parse(h)}catch(b){a={}}else a={"":h};for(const [b,d]of Object.entries(a))c("CUSTOM_CSS"+b.replace(/\W/g,"_"),{g:"Custom css"+(b?": ":"")+b,h:d,l:d.includes("FEATURE_ACTIVE")})}c("ZOOM_IN",{g:"Zoom in and out by pressing +/- (or F7/F8).",i:()=>{document.addEventListener("keydown",function(a){if("+"===a.key||"F7"===a.key)u-=5,0===u&&(u=5),K(u),"F7"===a.key&&a.preventDefault();if("-"===a.key||"F8"===a.key)u+=5,55===u&&(u=50),K(u)})}});c("LOOT_SORT",{g:"Sort/Hide loot by pressing F1.",
h:"#sdm--item-container {\n    top: 200px;\n    left: 250px;\n    right: 250px;\n    pointerEvents: none;\n    z-index: 2000;\n    position: absolute;\n    display: flex;\n    flex-wrap: wrap;\n}\n\n#sdm--item-container > div {\n    transform: none !important;\n    position: unset !important;\n    background-color: rgba(255, 255, 255, 0.2);\n}\n\n#sdm--item-container > div > .stein-dropped-item {\n    position: unset !important;  \n}",i:()=>{const a=document.createElement("div"),b=document.getElementById("stein-ui-overlay-container");
a.id="sdm--item-container";t.appendChild(a);let d=!0;document.addEventListener("keydown",function(g){if("F1"===g.key){g.preventDefault();d=!d;var l=ca("#stein-ui-overlay-container > .stein-dropped-item-container");if(0!==l.length)if(d)for(var n of l)n.style.display="none";else{n=Math.floor(Math.ceil(Math.sqrt(l.length+1))/2);var [,v,J]=b.style.transform.match(/translate\(([ \d.-]+)p?x?,([ \d.-]+)p?x?\)/);v=-parseFloat(v)+t.clientWidth/2;J=-parseFloat(J)+t.clientHeight/2;g=-n;var q=-n;for(const da of l){l=
v+50*g;const ka=J+50*q;da.style.display="";da.style.transform=`translate(${l}px, ${ka}px)`;g++;g>n?(g=-n,q++):0===g&&0===q&&g++}}}})}});c("RANGE_OVERLAY_10",{g:"Range overlay 10",l:!0,h:"FEATURE_ACTIVE #--sdm-overlay-range-10 { display: unset; }",i:()=>{E("--sdm-overlay-range-10",'<path d="M -35 -105\nH  35 V  -95 H  55 V -85 H  65 V -75 H  75 V -65 H  85 V -55 H  95 V -35 H  105\nV  35 H   95 V  55 H  85 V  65 H  75 V  75 H  65 V  85 H  55 V  95 H  35 V  105\nH -35 V   95 H -55 V  85 H -65 V  75 H -75 V  65 H -85 V  55 H -95 V  35 H -105\nV -35 H  -95 V -55 H -85 V -65 H -75 V -75 H -65 V -85 H -55 V -95 H -35 V -105" fill="none" stroke-width="0.3" stroke="red"/>')}});
c("RANGE_OVERLAY_8",{g:"Range overlay 8",l:!0,h:"FEATURE_ACTIVE #--sdm-overlay-range-8 { display: unset; }",i:()=>{E("--sdm-overlay-range-8",'<path d="M -25 -85\nH  25 V  -75 H  45 V -65 H  55 V -55 H  65 V -45 H  75 V -25 H  85 V -25 H  85\nV  25 H   75 V  45 H  65 V  55 H  55 V  65 H  45 V  75 H  25 V  85 H  25 V  85\nH -25 V   75 H -45 V  65 H -55 V  55 H -65 V  45 H -75 V  25 H -85 V  25 H -85\nV -25 H  -75 V -45 H -65 V -55 H -55 V -65 H -45 V -75 H -25 V -85 H -25 V -85" fill="none" stroke-width="0.3" stroke="black"/>')}});
c("RANGE_OVERLAY_6",{g:"Range overlay 6",l:!0,h:"FEATURE_ACTIVE #--sdm-overlay-range-6 { display: unset; }",i:()=>{E("--sdm-overlay-range-6",'<path d="M -25 -65\nH  25 V  -55 H  45 V -45 H  55 V -25  H  65\nV  25 H   55 V  45 H  45 V  55 H  25  V  65\nH -25 V   55 H -45 V  45 H -55 V  25  H -65\nV -25 H  -55 V -45 H -45 V -55 H -25  V -65" fill="none" stroke-width="0.3" stroke="red"/>')}});c("RANGE_OVERLAY_3",{g:"Range overlay 3",l:!0,h:"FEATURE_ACTIVE #--sdm-overlay-range-3 { display: unset; }",
i:()=>{E("--sdm-overlay-range-3",'<path d="M -15 -35\nH  15 V -25 H  25 V -15 H  35\nV  15 H  25 V  25 H  15 V  35\nH -15 V  25 H -25 V  15 H -35\nV -15 H -25 V -25 H -15 V -35" fill="none" stroke-width="0.3" stroke="black"/>')}});c("DIAGONAL_OVERLAY",{g:"Diagonal overlay",l:!0,h:"FEATURE_ACTIVE #--sdm-overlay-diagonal { display: unset; }",i:()=>{E("--sdm-overlay-diagonal",'<path d="M -110 -110 L 110 110" fill="none" stroke-width="0.3" stroke="red"/>\n<path d="M -110  110 L 110 -110" fill="none" stroke-width="0.3" stroke="red"/>')}});
var k=x.getItem("sdm--custom-overlay");k&&c("CUSTOM_OVERLAY",{g:"Custom overlay (localStorage: sdm--custom-overlay)",l:!0,h:"FEATURE_ACTIVE #--sdm-overlay-custom { display: unset; }",i:()=>{E("--sdm-overlay-custom",k)}});(r.RANGE_OVERLAY_10?.o||r.RANGE_OVERLAY_8?.o||r.RANGE_OVERLAY_6?.o||r.RANGE_OVERLAY_3?.o||r.CUSTOM_OVERLAY?.o)&&c("SVG_OVERLAY_COMMON",{u:!1,h:".--sdm-svg-overlay {\n      position: fixed;\n      width: calc(max(1vw, 1vh) * 10 / 3 * 22);\n      height: calc(max(1vw, 1vh) * 10 / 3 * 22);\n      top: calc(50vh - max(1vw, 1vh) * 10 / 3 * 22 / 2);\n      left: calc(50vw - max(1vw, 1vh) * 10 / 3 * 22 / 2);\n      z-index: 1;\n      pointer-events: none;\n      display: none;\n    }"});
r.ZOOM_IN?.o&&c("SAVE_ZOOM",{g:"Save zoom level.",i:()=>{const a=parseInt(x.getItem("smd--render-distance"),10)||u;a!==u&&(u=a,"undefined"!==typeof setRenderDistance?(K(a),setTimeout(()=>{K(a)},50)):setTimeout(()=>{K(a)},2E3))}});c("INFO",{u:!1,g:"ENABLING/DISABLING features requires refreshing page!"});if(Array.isArray(window.SteinDamageMeterCustomPlugins))for(const [a,b]of window.SteinDamageMeterCustomPlugins)"string"===typeof a&&b?c(`PLUGIN:${a}`,b):console.error("SteinDamageMeterCustomPlugins invalid entry",
a,b);if(!Y){0<X.length&&(h=document.createElement("style"),h.appendChild(document.createTextNode(X.join("\n\n"))),document.head.appendChild(h));try{for(const a of m)a()}catch(a){console.error(a);return}Q()}}},y)}})()}catch(L){console.error("DAMAGE METER ERROR",L)};}).call(this);
